name: Build and package EXTRA_MISC plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin.yml@main
    with:
      plugin_name: extra-misc
      plugin_directory: extra_misc
      build_target: extra_misc
      plugin_library: extra_misc.so

      sdk_image: quay.io/lefred14/mariadb-plugin-build
      mariadb_versions: |
          13.0.2
          13.1.1
          
      cmake_options: -DPLUGIN_DATE_EXTRA=DYNAMIC
      test_suite: extra_misc
      run_tests: false
